"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-8dr)bkahai1t6s-433%b(#*8_27vj%ieudn^bwdqi#&sg1c-a^'
# Используется для шифрования сессий и других важных данных
# в приложении

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# Пока вы разрабатываете приложение - выводит информацию об
# ошибках. Как только установите False проект перейдет в деплой
# состояние и ошибки не будут показываться пользователю


ALLOWED_HOSTS = []
# Этот параметр имен или IP адресов которые будут обслуживаться
# проектом Django. Если он пустой проект будет обслуживать
# любой адрес. Чтобы этого не произошло и никто не мог атаковать
# Проект то лучше указать свое доменное имя

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', # Дает Админ панель
    'django.contrib.auth',  # Дает стандартную логику авторизации и регистрации
    'django.contrib.contenttypes', # Связывает логику моделей с контентом
    'django.contrib.sessions',  # Дает управление сеансами пользователей
    'django.contrib.messages',  # Дает возможность отправки уведомлений
    'django.contrib.staticfiles',  # Дает возможность работы с CSS JS Images
    'courses', # Наше приложение
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'  # Указывает путь до главного файла с путями

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates'# Указываем где лежат главные шаблоны
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Django поддерживает 4 базы данных ссылка выше на документацию по
# подключению Sqlite3 Postgres Oracle MySql
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
# Стандартные условия на пароли, чтобы не были простыми, из чисел и короткими
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'  # Какой путь будет у статического файла
STATIC_ROOT = BASE_DIR / 'static'  # Где Django искать этот статический файл

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
